### PR TITLE
Added the "alexa_sequence" service to start flashbriefing via HA

### PR DESCRIPTION
**Pull request by lubeda**

### CODE REVIEW

**Comment by lubeda** [comment]
the README.md must not be merged!

**Comment by alandtse** [comment]
@lubeda Can you [enable edits](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) to your pull request? I have some minor edits reverting the README.md and extending the schema.

@keatontaylor I tested this with my edits and it works on my end. Let me know if you want me to merge after I get my edits in or let you handle merges.

**Comment by alandtse** [comment]
@keatontaylor I don't disagree. However, I'm not sure this functionality squarely falls into another component yet. Something like the last_echo command may make sense as a sensor.  This feels like it's still a media_player component. Not to mention, having users debug multiple alexa python files spread across the custom_component structure will be a bit more painful.

That said, the split shouldn't be too difficult to accomplish. I still think the API split needs to happen first. I'd also like HA to expose the Config flow component to custom_components so we can ditch the configurator.

**Comment by alandtse** [comment]
@lubeda thanks for contributing this. As we are doing a platform rewrite, I went ahead and implemented this in the my dev build. I also managed to implement it using the play_media service that already exists. I'll be documenting this in the next day or so in the wiki after further testing.

**Pull request closed without merging**
