### PR TITLE
Fixing folder names for 0.88

### PR DESCRIPTION
**Pull request by TheFuzz4**
Updated the folder naming structure for HA 0.88.

### CODE REVIEW

**Comment by RowdyDog12** [comment]
This would be a great idea!

**Comment by alandtse** [comment]
Thanks for putting this together.  However, as we are about to release a major rearchitecture as 1.X.X, I think we may not incorporate it into the 0.X.X branch to maintain some backward compatibility with versions of HA < 0.88.0. 

We may done one more point maintenance release as I think the fixes for 0.88.0 may not be backward compatible, and if we do, we'll see if we can merge this in.

**Comment by alandtse** [comment]
One other comment, we had to avoid the `alexa` base name as it will conflict with the existing component.  Per the architecture change announcement, you need to completely override the existing component so this fix will break at some point in the future since we are not ready to integrate into the `alexa` component yet.

In the 1.0.0 branch (#73), we are using `alexa_media` for now.

**Comment by TheFuzz4** [comment]
Cool no worries :) . just wanted to contribute.  I'm also going to rename my local to alexa_media as that is good to know.  Thanks.

**Pull request closed without merging**
