### PR TITLE
Update to breaking feature branch 1.0.0

### LINKED ISSUE #14: Move the Alexa API to a standalone pip module.

### LINKED ISSUE #37: Allow for multiple accounts using the component
I have a use case where I have echos that are on distinct accounts to intentionally restrict them from smarthome features, so that my kids can't torture each other, but I would love to be able remotely control them. Can the ability to have multiple accounts be added?

### LINKED ISSUE #43: Possibility to control volume while media_player in standby mode
Thank you for your work put in to this component.

Please add possibility to change Echo device volume while it is in `standby` state.

Currently volume can be changed when media_player in Home Assistant is in state `playing` and `paused` but in order to make alexa_tts service constantly speak text at certain volume.

### LINKED ISSUE #63: Switching account in configuration does not change logged in account
Changing the [configuration settings will continue to use prior cookies to log in](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/1712).  We should perform a check on logged in user and if it doesn't match, log out and delete the cookie. We recently added a check for the logged in user so that can be reused.

This probably makes sense to deal with the multi-account login logic #37 at the same time.

### LINKED ISSUE #70: Reduce polling across component
The get_last_called Alexa request is not cached and will be pulled by every media_player refresh. This can result in excessive load if there are multiple echos on an account.

### PR DESCRIPTION
**Pull request by alandtse**
This requires 0.1.0 of [alexapy](https://gitlab.com/keatontaylor/alexapy/merge_requests/2) and **HA >= 0.88.0**.

[Changes](https://github.com/keatontaylor/custom_components/wiki/Changelog#100-in-dev).
* Split to platform and pypi API (resolves #14, #62)
* Add multiple account support (resolves #37)
* Fix bug where cookie login didn't detect changes in configuration (resolves #63)
* Reduce media player polling. Polling should restart using HA or voice, but not other Apps. (resolves #70)
* Add [sequence processing](https://github.com/keatontaylor/custom_components/wiki#sequence-commands-versions--100) for more programmatic support.
* Add [automation routine](https://github.com/keatontaylor/custom_components/wiki#automation-routines-versions--100) support.
* Allow for volume changes when media not playing or paused (resolves #43)
This tested in both my production and test systems. I have updated wiki too in preparation for this.

### CODE REVIEW

**Comment by alandtse** [comment]
I have not tested this on HA 0.87.0 as I don't upgrade until .1 point releases. I don't think we'll run into any issues though although there is one issue report on HA 0.87.0 on the current version 0.10.1.

**Comment by alandtse** [comment]
I'm also investigating the [recent architecture change](https://github.com/home-assistant/home-assistant/pull/20677) made in HA where all components are in their own subdirectory.

I haven't found the documentation yet explaining the change.

**Comment by drewrox2009** [comment]
Where can i find your revised code if this doesn't get merged?

**Comment by alandtse** [comment]
@drewrox2009 My dev branch. Instructions are in the [Wiki](https://github.com/keatontaylor/custom_components/wiki/Configuration#versions--100).

**Comment by alandtse** [comment]
The new architecture changes in HA 0.88.0 documented in #76 will break this version too. Working on fixing this and also adjusting to the new requirements.

**Comment by alandtse** [comment]
No, it's feature complete and tested on my systems along with one or two volunteers. I can merge it in whenever you want to transition. I think maybe we do it with the .88.0 HA release as we can merge in the .88 specific fixes too. I also am testing the package renaming requirements so I think we should get those in too.

We do need to update alexapy; I have a PR there on Gitlab. If you'd like me to help with the publishing on pypi, I can do that too. My pypi username matches my username here and on Gitlab.

**Comment by alandtse** [comment]
I've updated this to use the new directory format and the new constants.  This means this branch will only work with HA >= 0.88.0.  My thought is that is when we move this to master, we move the old master to 0.10.X so people can reference it still if they want the old build.

**Comment by alandtse** [comment]
For reference, HA architecture change is discussed [here](https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html).

**Comment by alandtse** [comment]
@keatontaylor HA 0.88.0 came out today. Do you agree with the rearchitecture coming out for this release since there will be breaking changes anyway? If so, we need to update the API on gitlab. (I don't have any contributor rights there or on pypi).

**Comment by chali272** [comment]
> @drewrox2009 My dev branch. Instructions are in the [Wiki](https://github.com/keatontaylor/custom_components/wiki/Configuration#versions--100).

This looks awesome! 
does this work for hass.io?    how do i install this on hass.io 

//Regards

**Comment by alandtse** [comment]
I do not use a hass.io environment, so I don't have instructions. Assuming hass.io supports custom_components, then yes it will work.

**Comment by chali272** [comment]
> I do not use a hass.io environment, so I don't have instructions. Assuming hass.io supports custom_components, then yes it will work.

Hi, ok,  yes it support custome_component,   i used tha "Alexa media_player 0.9" but removed it to install your nice work.  but im missing something, i added this as with the "original" alexa mediaplayer  
in the folder Configuration/custome_components/alexa_media. i added this 3 fils:     
  __init__.py
    const.py
    media_player.py

but is it something else that needs to be installed on this version of "alexa_media player" or does it work as the old one 0.9 version.  (other than the small change in configuration.yaml, and folders)

this line: pip3 install --force git+https://gitlab.com/alandtse/alexapy.git
is this a necessary thing or is that only for updates? 

//Regards

**Comment by alandtse** [comment]
Yes, you have to install the new dependency if you want to use the 1.0.0 branch. The Wiki posted above explains all required steps to migrate. If you skip any (e.g., dependency, folder names, configuration.yaml), it will not work.

**Comment by chali272** [comment]
> Yes, you have to install the new dependency if you want to use the 1.0.0 branch. The Wiki posted above explains all required steps to migrate. If you skip any (e.g., dependency, folder names, configuration.yaml), it will not work.

ok, i did folow the guide and run the install script, and it stat it installs, but im getting this on reboot,
(i placed the 3 fils in at folder cald alexa_media in and placed it under Configuration/custome_components/    and added 

alexa_media:
  accounts:
    - email: my email
      password: my password
      url: amazon.com

to the configuration.yaml fil.    

in the wiki it stats "place the above info to the alexa_media domain"
im guessing the "alexa_domain" mean ad the info as above in the configuration.yaml fil?

Japp im very new to this ;-)  thank for taking your time to help me with this.

//Regards
 

Sat Feb 23 2019 01:28:45 GMT+0100 (centraleuropeisk normaltid)
Unable to install package alexapy==0.1.0: Could not find a version that satisfies the requirement alexapy==0.1.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5)
No matching distribution found for alexapy==0.1.0
You are using pip version 19.0.2, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by keatontaylor** [comment]
Pipeline currently running for gitlab project version tagged 0.1.0.

**Comment by alandtse** [comment]
@chali272 Please note, while I'd like to help, this build is a developer build which implies you are able to self-debug your environment.  Also, this thread is intended to discuss the pull request and not as a general support thread.  To avoid further clutter, I will respond one last time but I do not plan to respond further.

> Unable to install package alexapy==0.1.0: Could not find a version that satisfies the requirement alexapy==0.1.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5)
> No matching distribution found for alexapy==0.1.0
> You are using pip version 19.0.2, however version 19.0.3 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.

The error message indicates the dependency is not installed. You'll need to ensure you install the dependency given any virtual environments hass.io may use.

> (i placed the 3 fils in at folder cald alexa_media in and placed it under Configuration/custome_components/ and added
> 
> alexa_media:
> accounts:
> - email: my email
> password: my password
> url: amazon.com
> 
- Spelling is important for file names and configuration settings.
- Indentation is important for the configuration.yaml. Please follow the wiki. But yes, the platform should be `alexa_media` per the wiki.

**Comment by alandtse** [comment]
@keatontaylor Will do. I'll run another test to make sure pypi is pulling correctly during HA upgrade and merge after.

**Comment by chali272** [comment]
thanks. made it work 2min after i posted ;-). had to do it in other way since I'm running docker. don't know if you like reports on multiple accounts? if you don't want that info posted here i will remove it. After testing to ad 3 accounts, first 2 shows up. but not the 3rd. # out the first accounts the 3rd shows up. removed  # from the 2 first accounts. the 3rd disperse.   going to retest this a couple of times to see if its possible to get it to work on all 3. thanks again for creating this //regards

**Comment by alandtse** [comment]
@chali272 Please post an issue on the multiple accounts. We appreciate the report.

**Pull request merged**
