### PR TITLE
Add .last_called attribute

### PR DESCRIPTION
**Pull request by brianhanifin**
Do these changes resolve the changes you requested here (https://github.com/keatontaylor/custom_components/pull/61#pullrequestreview-193465945). If so, you are welcome to merge it.

BTW, I created a new repository to resolve some issues I was having.

### CODE REVIEW

**Comment by alandtse** [comment]
You're actually are still committing your ._.DS_Store file. 

I don't see a problem with updating the .gitignore file to capture macOS development (I do it on a mac), but you should git rm the ._.DS_store file.  Also, you're changing the permissions on the files.  See this [SO thread](https://stackoverflow.com/questions/1257592/how-do-i-remove-files-saying-old-mode-100755-new-mode-100644-from-unstaged-cha) for how to stop doing that.

Can you please fix those issues so your only submitting the changes for the .gitignore and alexa.py without the file permission changes?

Also, thanks for fixing some of the pylint errors.

@keatontaylor after the fixes I think we can just do a squashed commit to get this in. Afterward, I'll use this commit as the base for breaking up the platform.

**Comment by brianhanifin** [comment]
I'm working on these now.

**Comment by brianhanifin** [comment]
@alandtse OK. I made those changes and it looks like the files in this pull request have been updated. Does this resolve https://github.com/keatontaylor/custom_components/pull/64#issuecomment-456265654?

In retrospect, I should have created a separate branch. It has been a few years since I've shared a repo with others. If you want, I can do that and resubmit later today.

**Comment by brianhanifin** [comment]
OK. I will try a hard reset in the morning.

**Comment by alandtse** [comment]
I'll merge this in and do a version increment after @brianhanifin does another try on the permissions. We can just revert it back in the next release anyway.

**Pull request closed without merging**
